og_itinerary= []
print("Please input your 5 travel destinations:")
for i in range(1,6):
    og_location = input(f"Destination {i}:")
    og_itinerary.append(og_location)
print("Original Travel Itinerary:")
print("1.", og_itinerary[0])
print("2.", og_itinerary[1])
print("3.", og_itinerary[2])
print("4.", og_itinerary[3])
print("5.", og_itinerary[4])
print("Let's update your 2nd and 5th destinations.")
new_location1 =input("Enter a new destination for position number 2:")
new_location2=input("Enter a new destination for position number 5:")
og_itinerary.pop(4)
og_itinerary.pop(1)
og_itinerary.insert(1, new_location1)
og_itinerary.insert(4, new_location2)

print("Updated Travel Itinerary:")
print("1.", og_itinerary[0])
print("2.", og_itinerary[1])
print("3.", og_itinerary[2])
print("4.", og_itinerary[3])
print("5.", og_itinerary[4])